### ISSUE TITLE
Is this project complete and can I deploy it via opentelemetry-operator?

### ISSUE THREAD

**Issue by novohool** [open-telemetry/opentelemetry-network#253]
### Describe the issue you're reporting

```
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: simplest
spec:
  mode: daemonset
  config: |
    receivers:
      otlp:
        protocols:
           ebpf:
           dns:
```
