### ISSUE TITLE
dest_workload_name  unknown

### ISSUE THREAD

**Issue by letian0805** [open-telemetry/opentelemetry-network#324]
## Description
When the domain name is resolved and the IP is obtained, the monitoring data of the TCP connection shows dest_workload_name="(unknown)".
## Steps to Reproduce
1. Access aws rds in the container service.
2. View the tcp_bytes metric.
## Expected Result
dest_workload_name should be a domain name or IP address, not unknown.
## Actual Result
(unknown)

### eBPF Collector version

v0.10.2

## Environment
OS: (e.g., "Ubuntu 20.04") kernel version    5.10.233-224.894.amzn2.x86_6
Compiler(if manually compiled): (e.g., "go 14.2")

### eBPF Collector configuration

```yaml
#reducer configuration

#telemetry_port: 8000

num_ingest_shards: 1

num_matching_shards: 1

num_aggregation_shards: 1

partitions_per_shard: 1

enable_id_id: false

enable_az_id: false

enable_flow_logs: false

enable_otlp_grpc_metrics: false

otlp_grpc_metrics_address: "localhost"

otlp_grpc_metrics_port: 4317

otlp_grpc_batch_size: 1000

enable_otlp_grpc_metric_descriptions: false

disable_prometheus_metrics: false

shard_prometheus_metrics: false

prom_bind: "0.0.0.0:7010"

#scrape_size_limit_bytes: 0

#internal_prom_bind: "0.0.0.0:7001"

#stats_scrape_size_limit_bytes: 0

scrape_metrics_tsdb_format: "prometheus"

disable_node_ip_field: false

enable_autonomous_system_ip: true

#geoip_path: ""

enable_aws_enrichment: true

enable_percentile_latencies: false

disable_metrics: "http.all,udp.all,tcp.all,dns.all"

enable_metrics: "tcp.bytes,tcp.new_sockets,tcp.active,udp.bytes,dns.responses"

index_dump_interval: 0
```

### Log output

```shell

```
